use_frameworks!

platform :ios, '10.0'

target 'scm-lib_Example' do
  pod 'scm-lib', :path => '../'

  target 'scm-lib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
